# Generated by Django 3.2.2 on 2021-05-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totaPrice',
            new_name='totalPrice',
        ),
    ]
